juju add-machine node02
juju add-machine node03
juju add-machine node04
juju add-machine node05
juju add-machine node06
juju add-machine node07
juju add-machine node08
juju add-machine node09
juju add-machine node10
juju add-machine node11
juju add-machine node12
juju add-machine node13
juju add-machine node14
