neutron-gateway:
  data-port: br-ex:ens6
  bridge-mappings: physnet1:br-ex
  openstack-origin: cloud:focal-victoria
neutron-api:
  default-tenant-network-type: vxlan
  enable-l3ha: true
  flat-network-providers: physnet1
  max-l3-agents-per-router: 3
  neutron-security-groups: true
  openstack-origin: cloud:focal-victoria
  overlay-network-type: vxlan
  vip: 192.168.10.135
neutron-hacluster:
  corosync_transport: unicast
