ovn-chassis:
  bridge-interface-mappings: br-ex:ens6
  ovn-bridge-mappings: physnet1:br-ex
  openstack-origin: cloud:focal-victoria
neutron-api:
  enable-l3ha: true
  flat-network-providers: physnet1
  max-l3-agents-per-router: 3
  neutron-security-groups: true
  openstack-origin: cloud:focal-victoria
  vip: 192.168.10.235
ovn-central:
  source: cloud:focal-victoria
neutron-hacluster:
  corosync_transport: unicast
